// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjdhPiTQhHflKL3MRxDNyLko1xG2MR-X4',
    appId: '1:215256200314:android:44fa8e0c8d7b1a653cb7c3',
    messagingSenderId: '215256200314',
    projectId: 'instagram-599a7',
    storageBucket: 'instagram-599a7.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw4zJobGvxNT7bRwdJyWCU4TGfpCFfXUc',
    appId: '1:215256200314:web:4a19d30bd457ce893cb7c3',
    messagingSenderId: '215256200314',
    projectId: 'instagram-599a7',
    authDomain: 'instagram-599a7.firebaseapp.com',
    storageBucket: 'instagram-599a7.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjbMNqeZPTZ6-yszbtvqSzZz-ygpoQTaI',
    appId: '1:215256200314:ios:6fe4ea139ab78cf03cb7c3',
    messagingSenderId: '215256200314',
    projectId: 'instagram-599a7',
    storageBucket: 'instagram-599a7.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAdminApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjbMNqeZPTZ6-yszbtvqSzZz-ygpoQTaI',
    appId: '1:215256200314:ios:6fe4ea139ab78cf03cb7c3',
    messagingSenderId: '215256200314',
    projectId: 'instagram-599a7',
    storageBucket: 'instagram-599a7.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAdminApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw4zJobGvxNT7bRwdJyWCU4TGfpCFfXUc',
    appId: '1:215256200314:web:077b078b1c0e8e673cb7c3',
    messagingSenderId: '215256200314',
    projectId: 'instagram-599a7',
    authDomain: 'instagram-599a7.firebaseapp.com',
    storageBucket: 'instagram-599a7.firebasestorage.app',
  );

}